config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

  def badge_color
    case status
    when "not-started"
      "secondary"
    when "in-progress"
      "warning"
    when "complete"
      "success"
    end
  end

  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete? }
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [['Not started', 'not-started'],
                    ['In progress', 'in-progress'],
                    ['Complete', 'complete']]

  def badge_color
    case status
    when "not-started"
      "secondary"
    when "in-progress"
      "warning"
    when "complete"
      "success"
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    redirect_to projects_url, notice: 'Project was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project

    @project = current_user.projects.find(params[:id])

  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project, notice: 'Task was successfully destroyed.', status: :see_other
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def task_params
    params.require(:task).permit(:name, :description, :status, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_footer.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
  <symbol id="linkedin" viewBox="0 0 16 16">
    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
  </symbol>
  <symbol id="github" viewBox="0 0 16 16">
    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
  </symbol>
</svg>

<div class="container">
  <footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top ">
    <ul class="nav col-md-4 justify-content-center list-unstyled ">
      <li class="ms-3">
        <span class="text-muted">&copy; 2022 Paweł Mołek</span>
      </li>
      <li class="ms-3"><a class="text-muted" href="https://github.com/PawelMolek" target="_blank">
        <svg class="bi" width="24" height="24">
          <use xlink:href="#github"/>
        </svg>
      </a></li>
      <li class="ms-3">
        <a class="text-muted" href="https://www.linkedin.com/in/pawe%C5%82-mo%C5%82ek-737274142/" target="_blank">
          <svg class="bi" width="24" height="24">
            <use xlink:href="#linkedin"/>
          </svg>
        </a></li>
    </ul>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">

    <div class="container pt-5">

      <div class="d-flex flex-row-reverse">

        <% if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-dark mb-5" %>
        <% end %>

      </div>
      <% if notice.present? %>
        <div class="alert alert-success"><%= notice %></div>
      <%end %>
      <% if alert.present? %>
        <div class="alert alert-warning"><%= alert %></div>
      <%end %>

      <%= yield %>

    </div>
    <footer class="footer">
        <%= render "home/footer" %>
      </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class:"form-control mb-2"%>
  </div>

  <div class="action">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<table class="table">
  <tbody>
  <tr>
    <th scope="row">Name</th>
    <td><%= project.name %></td>
  </tr>
  <tr>
    <th scope="row">Description</th>
    <td><%= project.description %></td>
  </tr>
  </tbody>
</table>

app/views/projects/edit.html.erb
<%= link_to "Back to projects", @project, class: "btn btn-secondary mb-3" %>
<div class="card">
  <div class="card-body">
    <h2 class="card-tile mb-4">
      <span>Editing Project</span>
    </h2>
    <%= render "form", project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-header">
    <h2 class="card-tile d-flex justify-content-between mb-4">
      <span>Projects</span>
      <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
    </h2>
  </div>
  <div class="card-body">
    <% @projects.each do |project| %>
      <%= link_to project, class: "text-decoration-none" do %>
        <div class="card project-card mb-2">
          <div class="card-body">
            <div class="mb-3">
              <div class="mb-3">
              <span class="badge alert-<%= project.badge_color %>">
                <%= project.status %>
              </span>
                <span class='text-secondary'>
                <small>
                  <%= project.percent_complete %>% complete
                  (<%= project.total_complete %>/<%= project.total_tasks %> tasks)
                </small>
              </span>
              </div>
              <h4 class="card-title text-dark fw-b"><%= project.name %></h4>
              <p class="text-secondary"><%= project.description %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= link_to "Back to projects", projects_path, class: "btn btn-secondary mb-3" %>
<div class="card">
  <div class="card-body">
    <h2 class="card-tile mb-4">
      <span>New Project</span>
    </h2>
    <%= render "form", project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<%= link_to "Back", projects_path, class: "btn btn-secondary mb-2" %>
<div class="card mb-5">
  <div class="card-header">
    <h2 class="card-tile d-flex justify-content-between my-4">
      <span><%= @project.name %></span>
      <div>
        <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-dark" %>
        <%= link_to 'Delete', @project, data: { turbo_method: :delete, turbo_confirm: "Are you sure? " }, class: "btn btn-warning" %>
      </div>
    </h2>
  </div>
  <div class="card-body">
    <%= render @project %>
    <h6 class="mt-5">New Task</h6>
    <%= render "tasks/form" %>
    <hr>
    <div class="mt-4">
      <h4>Tasks</h4>
      <% @project.tasks.each do |task| %>
        <% if task.persisted? %>
          <div class="card mb-3">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <span class="badge alert-<%= task.badge_color %> mb-3"><%= task.status %></span>
                <div>
                  <%= link_to 'Edit', edit_project_task_path(task.project, task), class: "btn btn-dark btn-sm" %>
                  <%= link_to 'Delete', [task.project, task], data: { turbo_method: :delete, turbo_confirm: "Are you sure? " }, class: "btn btn-warning btn-sm" %>
                </div>
              </div>
              <h5 class="card-tile mb-2">
                <span><%= task.name %></span>
              </h5>
              <p class="mb-0"><%= task.description %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row mb-5">
    <div class="col"><%= f.text_field :name, class: "form-control", placeholder: "Enter task name..." %></div>
    <div class="col-6"><%= f.text_field :description, class: "form-control", placeholder: "Enter description..." %></div>
    <div class="col"><%= f.select :status, Task::STATUS_OPTIONS, {}, class: "form-select" %></div>
    <div class="col"><%= f.submit class: "btn btn-primary" %></div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= link_to "Back to projects", @project, class: "btn btn-secondary mb-3" %>

<div class="card">
  <div class="card-body">
    <h2 class="card-tile mb-4">
      <span>Editing Task</span>
    </h2>
    <%= render "form" %>
  </div>
  <%= link_to 'Delete', project_task_path(@project, @task), data: {turbo_method: :delete, turbo_confirm: "Are you sure? " }, class: "btn btn-warning" %>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>